In [5]:
from datasets.dataset_dict import DatasetDict
from datasets import Dataset, concatenate_datasets
import evaluate

import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.model_selection import train_test_split 
from transformers import pipeline, AutoTokenizer
import os

In [ ]:
# from huggingface_hub import notebook_login
# # If below code does not work, copy and paste this code in the terminal: huggingface-cli login 
# then paste this read token (you will have to construct it)


# notebook_login()

In [6]:
# load a list of passages and predict them (will take about .25 seconds per passage for me so beware the wait)
def predictor(data, labels, tokenizer_kwargs, classifier):
    dataOutput = []
    for text in data:
        # get actual labels
        actual_labels = [text[label] for label in labels]
        prediction = classifier(text['passage'], **tokenizer_kwargs)

        # get predicted labels
        scores = {item['label']:item['score'] for item in prediction[0]} #turn prediction into a dictionary
        pred_labels = [1 if scores[label] >= 0.5 else 0 for label in labels]

        
        output_dict = dict()
        output_dict["pred_labels"] = pred_labels
        output_dict["actual_labels"] = actual_labels
        output_dict["passage"] = text['passage']
        output_dict["ID"] = text['ID']


        # score[0][("actual_label", 'passage')] = text['passage'], text['label']
        dataOutput.append(output_dict)
    return dataOutput

# Get F1 scores
def score(dataOutput, labels):
    from sklearn.metrics import f1_score, accuracy_score

    df_score = pd.DataFrame(index=['NLP'], columns= [label+"_F1" for label in labels] + ["Micro_F1", "Macro_F1"])
    actual_labels = [x['actual_labels'] for x in dataOutput]
    pred_labels = [x['pred_labels'] for x in dataOutput]
    for index, label in enumerate(labels):
        f1 = round(f1_score(y_true=np.array(actual_labels)[:,index], y_pred=np.array(pred_labels)[:,index]),3)
        df_score.at['NLP', label+"_F1"] = f1
        # print(f"{label}: {(6 - len(label)) *' '}{f1}")

    # print("\n")

    f1_micro = round(f1_score(y_true=actual_labels, y_pred=pred_labels, average='micro'),3)
    f1_macro = round(f1_score(y_true=actual_labels, y_pred=pred_labels, average='macro'),3)
    f1_weighted = round(f1_score(y_true=actual_labels, y_pred=pred_labels, average='weighted'),3)
    df_score.at['NLP', "Micro_F1"] = f1_micro
    df_score.at['NLP', "Macro_F1"] = f1_macro
    df_score.at['NLP', "Weighted_F1"] = f1_weighted
    return df_score
def cor_score(dataOutput, labels):
    from sklearn.metrics import matthews_corrcoef
    df_score = pd.DataFrame(index=['NLP'], columns= [label+"_Cor" for label in labels])
    actual_labels = [x['actual_labels'] for x in dataOutput]
    pred_labels = [x['pred_labels'] for x in dataOutput]
    for index, label in enumerate(labels):
        corrcoef = round(matthews_corrcoef(y_true=np.array(actual_labels)[:,index], y_pred=np.array(pred_labels)[:,index]),3)
        df_score.at['NLP', label+"_Cor"] = corrcoef    
    return df_score
    # print(f'F1 score (micro) {f1_micro}\nF1 score (macro) {f1_macro}')

## Inference

### Load datset

In [3]:
import json
loc = ""
# loc = "../HRAF_MultiLabel_ThreeLargeClasses/" #load old threemain class (comment this out unless you specifically are using it)

# dataset = load_dataset('csv', data_files={'train': 'train.txt', 'validation': 'val.txt', 'test': 'test.txt'}, sep=";", 
#                               names=["text", "label"])


# f = open(loc+"Datasets/John Test Datasets/test_dataset.json") #John's dataset
f = open(loc+"Datasets/test_dataset.json")
# f = open("../HRAF_MultiLabel_ThreeLargeClasses/Datasets/test_dataset.json") #load old threemain class (comment this out unless you specifically are using it)
data = json.load(f)
f.close()
Hraf = Dataset.from_dict(data)
Hraf

Dataset({
    features: ['ID', 'passage', 'EVENT_Illness', 'EVENT_Accident', 'EVENT_Other', 'CAUSE_Material_Physical', 'CAUSE_Spirits_Gods', 'CAUSE_Witchcraft_Sorcery', 'CAUSE_Rule_Violation_Taboo', 'ACTION_Physical_Material', 'ACTION_Technical_Specialist', 'ACTION_Divination', 'ACTION_Shaman_Medium_Healer', 'ACTION_Priest_High_Religion'],
    num_rows: 2074
})

### Get John Data

In [5]:
# Get John Dataset
path = "../../GOLDEN_DATASET/data/objects/tiered/tiered_scored_embedded_cleaned_raw__Altogether_Dataset_RACoded_Combined_20251014_091039/"
# HRAF_NLP\HRAF_MultiLabel_SubClasses_Kfolds\
# GOLDEN_DATASET\data\objects\tiered\tiered_scored_embedded_cleaned_raw__Altogether_Dataset_RACoded_Combined_20251014_091039\tier1.xlsx
df_tier1 = pd.read_excel(path+"tier1.xlsx")
df_tier2 = pd.read_excel(path+"tier2.xlsx")
df_John = pd.concat([df_tier1,df_tier2])
print(len(df_John))
df_John.head(2)

5000

,Passage,Unnamed: 0,Passage Number,Region,SubRegion,Culture,DocTitle,Section,Author,Page,...,Run_Number,Finished,Coder,Other_Comments.1,Dataset,Info,passage_id,confidence_composite,confidence_consistency,confidence_rerank
0,Their methods of inducing disease included ske...,7937,59046,North-America,Arctic and Subarctic,Ojibwa,Traditional Ojibwa religion and its historical...,Causes of Disease,"Vecsey, Christopher",147,...,3,1,LR,NaN,1,NaN,f2018acb0b00ec4a,0.847378,0.924037,0.770719
1,Informants report experiencing a variety of se...,1819,10904,Middle-America-and-the-Caribbean,Maya Area,Tzeltal,Interpretations of drinking performances in Ag...,The beginnings of a theory of illness for Agua...,"Metzger, Duane, 1930-",120,...,1,1,KK,NaN,1,NaN,d4dbaf7cb3b97073,0.837891,1.000000,0.675781

In [174]:

df_path = "../../Coding and Dataset/Data/"
# df_path = "../../../eHRAF_Scraper-Analysis-and-Prep/Data/"
dataFolder = r"(subjects-(contracts_OR_disabilities_OR_disasters_OR_friendships_OR_gift_giving_OR_infant_feeding_OR_lineages_OR_etc/"
# dataFolder = r'subjects-(sickness)_FILTERS-culture_level_samples(PSF)'


# Get model and centralized path if relevent
model_name = "HRAF_MultiLabel_SubClasses_Kfolds"
path = f"" #Path to centralized file locations (leave blank if centralized location is here)



# load df (only load one of these commented out lines)
# df = pd.read_excel(f"{df_path}{dataFolder}/_Altogether_Dataset_RACoded.xlsx", header=[0,1], index_col=0) # Fall 2023 sickness + non-sickness
df = pd.read_excel(f"{df_path}{dataFolder}/_Altogether_Dataset_RACoded_Combined.xlsx", header=[0,1], index_col=0) # Spring 2023 - Spring 2024  sickness + nonsickness dataset
print(len(df))
print(df[("CODER","Run_Number")].value_counts())
df.head(2)

11005
(CODER, Run_Number)
3    9028
1    1926
2      51
Name: count, dtype: int64

         CULTURE                               \
  Passage Number Region   SubRegion   Culture
0           1392   Asia  South Asia  Andamans
1           1393   Asia  South Asia  Andamans

                                                                     \
                                            DocTitle        Section
0  Hygiene and medical practices among the Onge (...  1. Habitation
1  Hygiene and medical practices among the Onge (...        3. Food

                               \
            Author Page  Year
0  Cipriani, Lidio  484  1961
1  Cipriani, Lidio  487  1961

                                                      ... ACTION  \
                                                 OCM  ...  Other
0  ['171', '301', '727', '751', '765', '775', '777']  ...      1
1  ['136', '231', '271', '312', '415', '516', '751']  ...      0

                                                      \
                                         Description
0  Several customs are believed to connect with t...
1                             No action is mentioned

                                                      \
                                         Local_terms
0   ibidanghe: made from decorated human jawbone ...
1                                                  0

                                               OTHER      CODER           \
                                      Other_Comments Run_Number Finished
0  General note of this spreadsheet - many of the...          1     True
1                                                NaN          1     True

                   OTHER   CODER  \
  Coder Other_Comments.1 Dataset
0    YM              NaN       1
1    YM              NaN       1


                                                Info
0  Dataset 1: ['750', '751', '752', '753']   Coun...
1  Dataset 2: ['784', '731', '732', '777', '791',...

[2 rows x 43 columns]

In [ ]:
### Check for duplicates in run 2 which do not appear in BOTH run 1 and 3 (and thus are eroneously deleted, these are the 20 passages spoken about later)
# df_run1 = df.loc[df[("CODER","Run_Number")]==1]
# df_run2 = df.loc[df[("CODER","Run_Number")]==2]
# df_run3 = df.loc[df[("CODER","Run_Number")]==3]

# all3= df_run2[df_run2[("CULTURE","Passage")].isin(df_run1[("CULTURE","Passage")])][("CULTURE","Passage")].isin(df_run3[("CULTURE","Passage")])
# not3_index = all3[~all3].index
# df_not3 = df.iloc[list(not3_index)]
# df_not3[("CODER","Run_Number")].value_counts()

# # counter = 0
# # for i, value in enumerate(pass_try):
# #     passages = df.loc[df[("CULTURE","Passage")]==value]
# #     run_length =  len(passages)
    
# #     if run_length <3:
# #         counter += 1
# #         print("fail: ", all3_index[i])
# # print(counter)
# # df.loc[df[("CULTURE","Passage")]==pass_try]

(CODER, Run_Number)
2    20
Name: count, dtype: int64

In [175]:
# useRuns = [1,3] #Only include these runs (NOTE see note below as well, but THIS IS COMMENTED OUT IN ORDER TO NOT RUIN THE SUBLABEL DATASET BUT EVENTUALLY YOU SHOULD USE THIS CODE)
# df = df.loc[df[("CODER","Run_Number")].isin(useRuns)]

# NOTE: the resulting number of duplicates removed (at time of writing) is 617 yet 637 were removed (not counting the 1 extra special duplicate removed in values_to_remove).
# The extra 20 removed are from run 1 which had duplicates in run 2. These should have been kept and the msitake was due to the way ALL dulicates were marked for removal 
# but only run 3 duplicates were kept. The commented out code above actually would fix this issue, but since we don't want to change the dataset now that everything is trained, we will cannot remove

print("Starting Passages :",len(df))
print("Duplicate Passages:",sum((df.duplicated(("CULTURE","Passage")))))
# mask_NotDuplicate = ~(df.duplicated(("CULTURE","Passage"), keep=False))
mask_NotDuplicate = (df.duplicated(("CULTURE","Passage"), keep="first")) 
mask_Dataset2 = df[("CODER","Run_Number")]==3

# df = df[(mask_NotDuplicate) |  (mask_Dataset2)]
df = df[(~mask_NotDuplicate)]




# Remove certain passages which should not be in training or inference (these are duplicates that had to be manually found by a human)
# NOTE this normally would be ran, but John did not remove these passages and one is part of his chosen 5000 dataset unfortunately... SO, we will not remove
# values_to_remove = [3252, 33681, 6758, 10104]
# df = df[~df[('CULTURE','Passage Number')].isin(values_to_remove)]

print("Passages Remaining :",len(df))
print("Duplicate Passages:",sum((df.duplicated(("CULTURE","Passage")))))
df[("CODER","Run_Number")].value_counts()

Starting Passages : 11005
Duplicate Passages: 617
Passages Remaining : 10388
Duplicate Passages: 0

(CODER, Run_Number)
3    8462
1    1896
2      30
Name: count, dtype: int64

In [176]:
# Get original DF to match with John's
passages_John = df_John["Passage Number"]


df_Eric = df[df[("CULTURE","Passage Number")].isin(passages_John)]
print("Passages Remaining :",len(df_Eric))

Passages Remaining : 5000

In [177]:
df_John_indexed = df_John.set_index("Passage Number", drop=True)
df_Eric_indexed = df_Eric.set_index(("CULTURE","Passage Number"), drop=True)
df_Eric_indexed = df_Eric_indexed.loc[list(df_John_indexed.index)].reset_index()
df_Eric_indexed.head(3)

         CULTURE                                                          \
  Passage Number                            Region             SubRegion
0          59046                     North-America  Arctic and Subarctic
1          10904  Middle-America-and-the-Caribbean             Maya Area
2          54961                            Africa        Western Africa

                                                               \
   Culture                                           DocTitle
0   Ojibwa  Traditional Ojibwa religion and its historical...
1  Tzeltal  Interpretations of drinking performances in Ag...
2      Tiv                      A source book on Tiv religion

                                                                             \
                                             Section                 Author
0                                  Causes of Disease    Vecsey, Christopher
1  The beginnings of a theory of illness for Agua...  Metzger, Duane, 1930-
2                                             ICHIGH         Bohannan, Paul

                              ... ACTION  \
  Page  Year             OCM  ...  Other
0  147  1983  ['753', '754']  ...      0
1  120  1964         ['753']  ...      1
2  322  1969         ['753']  ...      0

                                                                  \
                                         Description Local_terms
0                                no action mentioned           0
1  Strategies for reducing illness are pursued ba...           0
2             no mention of how sickness was treated           0

           OTHER      CODER                           OTHER   CODER
  Other_Comments Run_Number Finished Coder Other_Comments.1 Dataset Info
0              0          3     True    LR              NaN       1  NaN
1            NaN          1     True    KK              NaN       1  NaN
2            NaN          3     True    JM              NaN       1  NaN

[3 rows x 43 columns]

In [178]:
#Construct col list
cols = list(df.columns)
id_index = cols.index(('CULTURE', "Passage Number"))
passage_index = cols.index(('CULTURE', "Passage"))
event_index =  cols.index(('EVENT', "No_Info"))
cause_index = cols.index(('CAUSE', "No_Info"))
action_index = cols.index(('ACTION', "No_Info"))
# get a list of all the multi-indexed column names we want to evaluate
# col_list = [cols[id_index]] + [cols[passage_index]] + cols[event_index:event_index+4] + cols[cause_index:cause_index+7] + cols[action_index:action_index+7] #to include all columns including No_info
col_list = [cols[id_index]] + [cols[passage_index]] + cols[event_index+1:event_index+4] + cols[cause_index+1:cause_index+7] + cols[action_index+1:action_index+7] # to include al columns BUT No_info


## Remove the following columns from the dataset. Based on the results of previous models ran and the bias of the categories
remv_cols = [("CAUSE","Just_Happens"),("CAUSE","Other"),("ACTION","Other")]
for remv in remv_cols:
    col_list.remove(remv)



# get column names to ascribe to the new data frame
colNames = ["ID","passage"]
for category, sub_cat in col_list:
    # skip passage and id which have already been added
    # print(category, sub_cat)
    if category == "CULTURE":
        continue
    if sub_cat == "No_Info":
        colNames += [category]#this to include main classes, we will hold off on that
        pass
    else:
        colNames += [f'{category}_{sub_cat}']

print("Columns excluded:\n", set(cols)-set(col_list),"\n")
# for col in col_list
print("Columns included:")
for col in colNames:
    print(col)
# colNames

Columns excluded:
 {('CULTURE', 'DocTitle'), ('CAUSE', 'Just_Happens'), ('OTHER', 'Other_Comments.1'), ('EVENT', 'Description'), ('CULTURE', 'Author'), ('CULTURE', 'SubRegion'), ('CULTURE', 'Section'), ('CODER', 'Info'), ('CULTURE', 'OCM'), ('CAUSE', 'Local_Terms'), ('CODER', 'Finished'), ('CULTURE', 'Culture'), ('CULTURE', 'OWC'), ('CAUSE', 'No_Info'), ('CODER', 'Run_Number'), ('ACTION', 'No_Info'), ('CODER', 'Dataset'), ('CAUSE', 'Other'), ('CULTURE', 'Page'), ('CULTURE', 'Region'), ('CAUSE', 'Description'), ('ACTION', 'Other'), ('ACTION', 'Local_terms'), ('CODER', 'Coder'), ('EVENT', 'Local_Terms'), ('ACTION', 'Description'), ('CULTURE', 'Year'), ('OTHER', 'Other_Comments'), ('EVENT', 'No_Info')}

Columns included:
ID
passage
EVENT_Illness
EVENT_Accident
EVENT_Other
CAUSE_Material_Physical
CAUSE_Spirits_Gods
CAUSE_Witchcraft_Sorcery
CAUSE_Rule_Violation_Taboo
ACTION_Physical_Material
ACTION_Technical_Specialist
ACTION_Divination
ACTION_Shaman_Medium_Healer
ACTION_Priest_High_Religion

In [179]:
# subdivide into just passage and outcome
df_small = pd.DataFrame()
df_small[colNames] = df_Eric_indexed[col_list]
# Flip the lable of "no_info"
# df_small[["EVENT","CAUSE","ACTION"]]  = df_small[["EVENT","CAUSE","ACTION"]].replace({0:1, 1:0})


# create train and validation/test sets (Also do John's as I want to double check we are splitting the same way)
train_val_E, test_E = train_test_split(df_small, test_size=0.2, random_state=42)
train_val_J, test_J = train_test_split(df_John, test_size=0.2, random_state=42)


# Create an NLP friendly dataset
Hraf = Dataset.from_dict(test_E.to_dict(orient= 'list'))
Hraf

Dataset({
    features: ['ID', 'passage', 'EVENT_Illness', 'EVENT_Accident', 'EVENT_Other', 'CAUSE_Material_Physical', 'CAUSE_Spirits_Gods', 'CAUSE_Witchcraft_Sorcery', 'CAUSE_Rule_Violation_Taboo', 'ACTION_Physical_Material', 'ACTION_Technical_Specialist', 'ACTION_Divination', 'ACTION_Shaman_Medium_Healer', 'ACTION_Priest_High_Religion'],
    num_rows: 1000
})

In [180]:
# Check to make sure the rows align with the John's (Should give 1000)
assert 1000 == len(test_E[test_E[("ID")].isin(test_J["Passage Number"])]), "Not same test split"

### Define Kwargs and Labels

In [4]:
# Define tokenizer kwargs
tokenizer_kwargs = {'padding':True,'truncation':True,'max_length':512}

classifier_kwargs = {'top_k':None, 'device':0} #Set device -1 for CPU, 0 or higher for GPU

# get label names
labels = [label for label in Hraf.features.keys() if label not in ['ID', 'passage']]
labels

['EVENT_Illness',
 'EVENT_Accident',
 'EVENT_Other',
 'CAUSE_Material_Physical',
 'CAUSE_Spirits_Gods',
 'CAUSE_Witchcraft_Sorcery',
 'CAUSE_Rule_Violation_Taboo',
 'ACTION_Physical_Material',
 'ACTION_Technical_Specialist',
 'ACTION_Divination',
 'ACTION_Shaman_Medium_Healer',
 'ACTION_Priest_High_Religion']

## Single Model Inference

Run this or the other model, not both

In [13]:
# # CHANGE Model name
# model = "Model_9_JohnRoberta/Test"
# checkpoint_path = "checkpoint-5000"
# # set up the pipeline from local



# CHANGE Model name (Roberta)
model = "Model_5_Roberta/Learning_Rate_2e-05_Weight_Decay_0.01_fold_1"
checkpoint_path = "checkpoint-12450"
# set up the pipeline from local
path =os.path.abspath(f"{model}/{checkpoint_path}")
classifier = pipeline("text-classification", model=path, **classifier_kwargs)


# sample inference ENTER TEXT IN HERE.
text = '''
“Drinking-tubes made of the leg-bones of swans (Fig. 109) are 190 also used chiefly as a measure of precaution against diseases ‘subject to shunning.’....”
'''
# reveal sample classification
prediction = classifier(text, **tokenizer_kwargs)
prediction

# # Demo other models (COMMENT THIS OUT UNLESS YOU REALLY WANT TO DEMO THIS)
# # Set up path from online hub (note, this is analogous but different model and is here because this is a demo)
# classifier = pipeline("text-classification", top_k=None, model="Chantland/Hraf_MultiLabel", use_auth_token="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", tokenizer=AutoTokenizer.from_pretrained("distilbert-base-uncased"))
# model = "MultiLabel_ThreeLargeClasses"

SafetensorError: Error while deserializing header: header too large

### Predict The Dataset

In [9]:
# Predict dataset (may take about .25 seconds per passage when tested on lab mac, could differ depending on your system)
# Also note that this pipeline is sequential and may give a warning saying it is unoptimized. Currently, using a whole dataset does not seem to reap faster results so we are remaining with sequential
HrafOutput = predictor(Hraf, labels=labels, tokenizer_kwargs=tokenizer_kwargs, classifier=classifier)
print(len(HrafOutput), "passages Predicted")

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

2074 passages Predicted

In [17]:
# HrafOutput = classifier(Hraf['passage'],**tokenizer_kwargs)
# print(len(HrafOutput), "passages Predicted")

### Calculate "Correctness" Metrics

In [10]:
#get F1 scores for labels.
df_score = score(HrafOutput, labels)
# Optional TEST, get correlational score instead)
df_score = score(HrafOutput, labels)
df_score

,EVENT_Illness_F1,EVENT_Accident_F1,CAUSE_Material_Physical_F1,CAUSE_Spirits_Gods_F1,CAUSE_Witchcraft_Sorcery_F1,CAUSE_Rule_Violation_Taboo_F1,ACTION_Physical_Material_F1,ACTION_Technical_Specialist_F1,ACTION_Shaman_Medium_Healer_F1,Micro_F1,Macro_F1,Weighted_F1
NLP,0.873,0.477,0.496,0.731,0.673,0.579,0.685,0.387,0.554,0.687,0.606,0.684

In [11]:
# Optional TEST, get correlational score instead)
df_score_cor = cor_score(HrafOutput, labels)
df_score_cor

,EVENT_Illness_Cor,EVENT_Accident_Cor,CAUSE_Material_Physical_Cor,CAUSE_Spirits_Gods_Cor,CAUSE_Witchcraft_Sorcery_Cor,CAUSE_Rule_Violation_Taboo_Cor,ACTION_Physical_Material_Cor,ACTION_Technical_Specialist_Cor,ACTION_Shaman_Medium_Healer_Cor
NLP,0.784,0.454,0.394,0.664,0.66,0.527,0.54,0.349,0.527

#### Add correctness to file

In [ ]:
# [x for x in df_oldScores.columns if x in df_scoresSep.columns]
# df_oldScores_merged = pd.concat([df_scoresSep, df_oldScores])
combined = pd.concat([df_oldScores, df_scoresSep], ignore_index=True)
combined

# df_oldScores_merged.columns[df_scoresSep.columns != 'Date']

,Date,EVENT_Illness_F1,EVENT_Accident_F1,EVENT_Other_F1,CAUSE_Material_Physical_F1,CAUSE_Spirits_Gods_F1,CAUSE_Witchcraft_Sorcery_F1,CAUSE_Rule_Violation_Taboo_F1,ACTION_Physical_Material_F1,ACTION_Technical_Specialist_F1,ACTION_Divination_F1,ACTION_Shaman_Medium_Healer_F1,ACTION_Priest_High_Religion_F1,Micro_F1,Macro_F1,Weighted_F1,test_length,train_length,Notes
Lexical search,2024-08-06 00:00:00,0.8,0.103,0.191,0.081,0.299,0.099,0.026,0.309,0.144,0.039,0.183,0.000,0.41,0.254,0.382,2074,8293,Ngram 1
NLP,2024-08-06 00:00:00,0.866,0.41,0.583,0.431,0.667,0.615,0.555,0.635,0.357,0.303,0.549,0.340,0.637,0.526,0.627,2074,8293,model: Model_3_LearningRates/Learning_Rate_2e-...
NLP,2024-05-29 00:00:00,0.856,0.355,0.574,0.394,0.681,0.59,0.493,0.628,0.396,0.000,0.479,0.193,0.622,0.47,NaN,2074,8293,model: Model_3_LearningRates/Learning_Rate_1e-...
NLP,2024-05-29 00:00:00,0.856,0.0,0.473,0.065,0.446,0.0,0.0,0.559,0.0,0.000,0.0,0.000,0.503,0.2,NaN,2074,8293,model: Model_2_ReducedCols/Weight_Decay_.01_fo...
NLP,2025-09-30,0.873,0.477,NaN,0.496,0.731,0.673,0.579,0.685,0.387,NaN,0.554,NaN,0.687,0.606,0.684,2074,8293,model: Model_9_JohnRoberta/Test/checkpoint-500...

In [32]:
df_oldScores_merged

,Date,EVENT_Illness_F1,EVENT_Accident_F1,CAUSE_Material_Physical_F1,CAUSE_Spirits_Gods_F1,CAUSE_Witchcraft_Sorcery_F1,CAUSE_Rule_Violation_Taboo_F1,ACTION_Physical_Material_F1,ACTION_Technical_Specialist_F1,ACTION_Shaman_Medium_Healer_F1,Micro_F1,Macro_F1,Weighted_F1,test_length,train_length,Notes,EVENT_Other_F1,ACTION_Divination_F1,ACTION_Priest_High_Religion_F1
NLP,2025-09-30,0.873,0.477,0.496,0.731,0.673,0.579,0.685,0.387,0.554,0.687,0.606,0.684,2074,8293,model: Model_9_JohnRoberta/Test/checkpoint-500...,NaN,NaN,NaN
Lexical search,2024-08-06 00:00:00,0.8,0.103,0.081,0.299,0.099,0.026,0.309,0.144,0.183,0.41,0.254,0.382,2074,8293,Ngram 1,0.191,0.039,0.000
NLP,2024-08-06 00:00:00,0.866,0.41,0.431,0.667,0.615,0.555,0.635,0.357,0.549,0.637,0.526,0.627,2074,8293,model: Model_3_LearningRates/Learning_Rate_2e-...,0.583,0.303,0.340
NLP,2024-05-29 00:00:00,0.856,0.355,0.394,0.681,0.59,0.493,0.628,0.396,0.479,0.622,0.47,NaN,2074,8293,model: Model_3_LearningRates/Learning_Rate_1e-...,0.574,0.000,0.193
NLP,2024-05-29 00:00:00,0.856,0.0,0.065,0.446,0.0,0.0,0.559,0.0,0.0,0.503,0.2,NaN,2074,8293,model: Model_2_ReducedCols/Weight_Decay_.01_fo...,0.473,0.000,0.000

In [35]:
df_scoresSep

,Date,EVENT_Illness_F1,EVENT_Accident_F1,CAUSE_Material_Physical_F1,CAUSE_Spirits_Gods_F1,CAUSE_Witchcraft_Sorcery_F1,CAUSE_Rule_Violation_Taboo_F1,ACTION_Physical_Material_F1,ACTION_Technical_Specialist_F1,ACTION_Shaman_Medium_Healer_F1,Micro_F1,Macro_F1,Weighted_F1,test_length,train_length,Notes
NLP,2025-09-30,0.873,0.477,0.496,0.731,0.673,0.579,0.685,0.387,0.554,0.687,0.606,0.684,2074,8293,model: Model_9_JohnRoberta/Test/checkpoint-500...

In [39]:
df_oldScores_merged['Date']  = df_oldScores_merged['Date'].astype('datetime64[ns]')
df_oldScores_merged.sort_values(by="Date", ascending=True)

,Date,EVENT_Illness_F1,EVENT_Accident_F1,CAUSE_Material_Physical_F1,CAUSE_Spirits_Gods_F1,CAUSE_Witchcraft_Sorcery_F1,CAUSE_Rule_Violation_Taboo_F1,ACTION_Physical_Material_F1,ACTION_Technical_Specialist_F1,ACTION_Shaman_Medium_Healer_F1,Micro_F1,Macro_F1,Weighted_F1,test_length,train_length,Notes,EVENT_Other_F1,ACTION_Divination_F1,ACTION_Priest_High_Religion_F1
NLP,2024-05-29,0.856,0.355,0.394,0.681,0.59,0.493,0.628,0.396,0.479,0.622,0.47,NaN,2074,8293,model: Model_3_LearningRates/Learning_Rate_1e-...,0.574,0.000,0.193
NLP,2024-05-29,0.856,0.0,0.065,0.446,0.0,0.0,0.559,0.0,0.0,0.503,0.2,NaN,2074,8293,model: Model_2_ReducedCols/Weight_Decay_.01_fo...,0.473,0.000,0.000
Lexical search,2024-08-06,0.8,0.103,0.081,0.299,0.099,0.026,0.309,0.144,0.183,0.41,0.254,0.382,2074,8293,Ngram 1,0.191,0.039,0.000
NLP,2024-08-06,0.866,0.41,0.431,0.667,0.615,0.555,0.635,0.357,0.549,0.637,0.526,0.627,2074,8293,model: Model_3_LearningRates/Learning_Rate_2e-...,0.583,0.303,0.340
NLP,2025-09-30,0.873,0.477,0.496,0.731,0.673,0.579,0.685,0.387,0.554,0.687,0.606,0.684,2074,8293,model: Model_9_JohnRoberta/Test/checkpoint-500...,NaN,NaN,NaN

In [41]:

# export F1 scores to excel
df_scoresSep = df_score.copy()
# first load train (and maybe add validation)
f = open(loc+"Datasets/train_dataset.json")
data = json.load(f)
train = Dataset.from_dict(data)
if os.path.isfile(loc+"Datasets/validation_dataset.json"):
    f = open(loc+"Datasets/validation_dataset.json")
    data = json.load(f)
    valid = Dataset.from_dict(data)
    train = concatenate_datasets([train, valid])
# add lengths of test and training set
df_scoresSep[["test_length", "train_length"]] = (len(Hraf), len(train))
# add date
df_scoresSep.insert(0, "Date", [datetime.today().date()])
if loc == "":
    df_scoresSep['Notes'] = f"model: {model}/{checkpoint_path}, Dataset: {model}"
else:
    df_scoresSep['Notes'] = f"model: {model}/{checkpoint_path}, Dataset: {loc}"
# load model_performance.xlsx or else create it
if os.path.isfile("Model_Prediction_Performance.xlsx"):
    df_oldScores = pd.read_excel("Model_Prediction_Performance.xlsx", index_col=0)
    
    df_oldScores_merged = pd.concat([df_oldScores, df_scoresSep], ignore_index=True)
    nonDateCols = df_oldScores_merged.columns[df_oldScores_merged.columns != 'Date']
    if any(df_oldScores_merged.duplicated(subset=nonDateCols)): # don't append the data unless it is new
        print("Duplicated scores found, skipping new addition")
        df_scoresSep = df_oldScores.copy()
    else:
        df_scoresSep = df_oldScores_merged.copy()
        df_scoresSep['Date'] = df_scoresSep['Date'].astype('datetime64[ns]')
        df_scoresSep.sort_values(by="Date", ascending=True)
        df_scoresSep.to_excel("Model_Prediction_Performance.xlsx")
else:
    df_scoresSep['Date'] = df_scoresSep['Date'].astype('datetime64[ns]')
    df_scoresSep.sort_values(by="Date", ascending=True)
    df_scoresSep.to_excel(f"Model_Prediction_Performance.xlsx")
df_scoresSep

,Date,EVENT_Illness_F1,EVENT_Accident_F1,EVENT_Other_F1,CAUSE_Material_Physical_F1,CAUSE_Spirits_Gods_F1,CAUSE_Witchcraft_Sorcery_F1,CAUSE_Rule_Violation_Taboo_F1,ACTION_Physical_Material_F1,ACTION_Technical_Specialist_F1,ACTION_Divination_F1,ACTION_Shaman_Medium_Healer_F1,ACTION_Priest_High_Religion_F1,Micro_F1,Macro_F1,Weighted_F1,test_length,train_length,Notes
0,2024-08-06,0.8,0.103,0.191,0.081,0.299,0.099,0.026,0.309,0.144,0.039,0.183,0.000,0.41,0.254,0.382,2074,8293,Ngram 1
1,2024-08-06,0.866,0.41,0.583,0.431,0.667,0.615,0.555,0.635,0.357,0.303,0.549,0.340,0.637,0.526,0.627,2074,8293,model: Model_3_LearningRates/Learning_Rate_2e-...
2,2024-05-29,0.856,0.355,0.574,0.394,0.681,0.59,0.493,0.628,0.396,0.000,0.479,0.193,0.622,0.47,NaN,2074,8293,model: Model_3_LearningRates/Learning_Rate_1e-...
3,2024-05-29,0.856,0.0,0.473,0.065,0.446,0.0,0.0,0.559,0.0,0.000,0.0,0.000,0.503,0.2,NaN,2074,8293,model: Model_2_ReducedCols/Weight_Decay_.01_fo...
4,2025-09-30,0.873,0.477,NaN,0.496,0.731,0.673,0.579,0.685,0.387,NaN,0.554,NaN,0.687,0.606,0.684,2074,8293,model: Model_9_JohnRoberta/Test/checkpoint-500...

## Checkpoint Multi-model Inference

This is to run over MANY models and checkpoints to test and see which is the strongest. This is ran instead of the single model one above and should NOT be ran together with the single model (simply because they do different things)

In [6]:
# code for running through all checkpoints
# code for running through all checkpoints
import os
import pandas as pd
import re
import json
from transformers import pipeline, AutoTokenizer
def checkpointInfer(path, data, labels, tokenizer_kwargs, classifier_kwargs, folds=True, output_str="output_dir_", modelDestinctifier:str= "ModelDistinctifierUnknown"):
    # Initiate Dataframe overall
    df = pd.DataFrame([])

    # Get all viable models
    # Makes sure the model starts with the output string and is a directory
    models = [name for name in os.listdir(path) if (name.startswith(output_str) and os.path.isdir(f"{path}/{name}"))]

    for model in models:
        # Initiate Dataframe for each model
        df_model = pd.DataFrame([])

        # Get checkpoint directory for a particular model and get the unit in which the model is distinguished (like learning rates)
        checkpoints_dir = [checkpoint for checkpoint in os.listdir(f"{path}/{model}") if checkpoint.startswith("checkpoint")]
        modelDestinctifier_unit = re.findall(f"{output_str}(.*?)_",model)
        try:
            modelDestinctifier_unit = float(modelDestinctifier_unit[0])
        except:
            pass


        # Predict for each checkpoint (within said model) and save results
        for checkpoint in checkpoints_dir:
            # Initiate Dataframe for each checkpoint
            df_checkpoint = pd.DataFrame([])
            # set up the pipeline from local
            model_path =os.path.abspath(f"{path}/{model}/{checkpoint}")
            classifier = pipeline("text-classification", model=model_path, **classifier_kwargs)
            # Get Predictions
            dataOutput = predictor(data, labels=labels, tokenizer_kwargs=tokenizer_kwargs, classifier=classifier)
            # Get scores
            df_checkpoint = score(dataOutput, labels)
            df_checkpoint = df_checkpoint.reset_index(drop=True) #remove the index here


            df_checkpoint.insert(0,modelDestinctifier,modelDestinctifier_unit) #insert model distinctifier (like weight decay or learning rate)
            #Extract and add Fold name if relevant
            if folds: #if using folds
                fold = re.findall(r"fold_(\d*)",model)
                fold = int(fold[0])
                df_checkpoint.insert(1,"Fold",fold)
            else:
                fold = ""

            # get checkpoint
            checkpoint_num = re.findall(r"checkpoint-(\d*)",checkpoint)
            assert len(checkpoint_num) == 1, f"More or less than one checkpoint numbers found: {len(checkpoint_num)} checkpoints"
            checkpoint_num = int(checkpoint_num[0])

            df_checkpoint.insert(0,"Model",model) # Add model name
            df_checkpoint.insert(0,"Checkpoint",checkpoint_num)
            df_model = pd.concat([df_model,df_checkpoint])
            print(model, checkpoint, "Complete")

        # concat model to overarching dataframe
        df = pd.concat([df,df_model])
        # save df for each model (as a checkpoint)
        # import evaluation if it exists
        if os.path.exists(f"{path}/Inference_Test.xlsx"):
            old_df = pd.read_excel(f"{path}/Inference_Test.xlsx", sheet_name="Sheet1", index_col=0)
            df_model = pd.concat([old_df, df_model])

        df_model.to_excel(f"{path}/Inference_Test.xlsx", sheet_name="Sheet1")
        print(model, "Successfully Saved")

    return df


            




# output_str="output_dir_"

# model = "MultiLabel_ThreeLargeClasses_kfoldsDEMO_WeightInvestigation"
# path =os.path.abspath(f"HRAF_Model_{model}")
# x = [name for name in os.listdir(path) if (name.startswith("output_dir_") and os.path.isdir(f"{path}/{name}"))]
# # x
# modelDestinctifier_unit = re.findall(f"{output_str}(.*?)_",x[1])
# try:
#     modelDestinctifier_unit = float(modelDestinctifier_unit)
# except:
#     pass

In [11]:
#This code will take a LONG time depending on how many models you have. It is recommended to use a GPU
path = loc+"/Model_3_LearningRates"
output_str = "Learning_Rate_"
modelDestinctifier = "Learning_Rate"

df_allScores = checkpointInfer(path=path, data=Hraf, labels=labels, tokenizer_kwargs=tokenizer_kwargs,  classifier_kwargs=classifier_kwargs, folds=True, output_str=output_str, modelDestinctifier= modelDestinctifier)
df_allScores

Weight_Decay_.01_fold_1 checkpoint-26430 Complete
Weight_Decay_.01_fold_1 Successfully Saved

,Checkpoint,Weight_Decay,Fold,EVENT_Illness_F1,EVENT_Accident_F1,EVENT_Other_F1,CAUSE_Just_Happens_F1,CAUSE_Material_Physical_F1,CAUSE_Spirits_Gods_F1,CAUSE_Witchcraft_Sorcery_F1,CAUSE_Rule_Violation_Taboo_F1,CAUSE_Other_F1,ACTION_Physical_Material_F1,ACTION_Technical_Specialist_F1,ACTION_Divination_F1,ACTION_Shaman_Medium_Healer_F1,ACTION_Priest_High_Religion_F1,ACTION_Other_F1,Micro_F1,Macro_F1
0,26430,0.01,1,0.865,0.0,0.494,0.0,0.059,0.591,0.0,0.0,0.0,0.567,0.0,0.0,0.046,0.0,0.0,0.501,0.175

## Optional File save

In [104]:
# HrafOutput

In [15]:
# optionally save the file to json
from transformers import AutoTokenizer
import copy

HrafOutput_dummy = copy.deepcopy(HrafOutput)

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def preprocess_function(examples):
    return tokenizer(examples["passage"], truncation=True)

tokenized_Hraf = Hraf.map(preprocess_function, batched=True)

for index, passage in enumerate(HrafOutput_dummy):
    assert passage['passage'] == tokenized_Hraf[index]['passage']
    passage['pred_labels'] = {key:passage['pred_labels'][index] for index, key in enumerate(labels)}
    passage['actual_labels'] = {key:passage['actual_labels'][index] for index, key in enumerate(labels)}
    passage['input_ids'] = tokenized_Hraf[index]['input_ids']

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Map:   0%|          | 0/728 [00:00<?, ? examples/s]

In [18]:
import json
# Save to unformatted json (uncomment)
with open(f"Datasets/tokenized_inputs.json", "w") as outfile:
    json.dump(HrafOutput_dummy, outfile)


# # Save to Dataset (uncomment)
# HrafOutput_dummy_dataset = Dataset.from_list(HrafOutput_dummy)
# Dataset.to_json(HrafOutput_dummy_dataset, f"Datasets/tokenized_Hraf")

## CHi Square

In [41]:
from scipy.stats import chi2_contingency

ct_EVENT_CAUSE = pd.crosstab(df[('EVENT','No_Info')], df[('CAUSE','No_Info')], rownames=['ACTION'], colnames=['CAUSE'])
ct_EVENT_CAUSE

array([[1167,  351],
       [  49,  183]], dtype=int64)

In [119]:
def chi_square_calc(row, col):
    cross_tab = pd.crosstab(df[(row,'No_Info')], df[(col,'No_Info')], rownames=[row], colnames=[col])
    stat, p, dof, expected = chi2_contingency(cross_tab)
    results = f"{row} by {col}:\nchi: {round(stat,1)}\np:   {round(p,3)}\n\n"
    return results

group_list = [('EVENT', 'CAUSE'), ('EVENT', 'ACTION'), ('ACTION', 'CAUSE')]
for row, col in group_list:
    print(chi_square_calc(row, col))

EVENT by CAUSE:
chi: 292.4
p:   0.0


EVENT by ACTION:
chi: 103.3
p:   0.0


ACTION by CAUSE:
chi: 0.0
p:   0.857

In [44]:
def chi_sqr(obs):
    size_x = obs.shape
    chi_mat = np.zeros(size_x)
    for row in range(size_x[0]):
        for col in range(size_x[1]):
            exp = np.sum(x[row]) * np.sum(x[:,col]) / np.sum(x)
            chi_mat[row, col] = np.sum((obs[row, col] - exp)**2 / exp)
    return chi_mat

print(np.sum(chi_sqr(x)))